services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    working_dir: /workspace
    networks:
      - zava-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=container
      - POSTGRES_URL=postgresql://store_manager:StoreManager123!@db:5432/zava
