site_name: Unlock your Agents Potential with MCP
site_author: Dave Glover
site_description: >-
  Azure AI Foundry Agent Services with MCP Workshop.


# Repository ..................................................
repo_name: Unlock your Agents Potential with MCP
repo_url: https://github.com/microsoft/aitour26-WRK540-unlock-your-agents-potential-with-model-context-protocol

# Copyright ...................................................
copyright: >
  Copyright &copy; 2023 - present Microsoft


nav:
  - Workshop Introduction: index.md
  - Workshop Navigation: navigating-the-workshop.md
  - Getting Started: 
    - Open the Workshop: getting-started.md
    - Star the GitHub Repo: getting_started-star-workshop.md
    - Architecture Overview: architecture.md
    - Deploy Agent Resources: getting-started-azure.md
    - Open VS Code Workspace: getting-started-workspace.md
  - Agent Services Labs:
    - AI Foundry Agent Services: agent-service-overview.md
    - Lab 1 Agent Instructions: lab-1-agent-instructions.md
    - Lab 2 Start your Agent: lab-2-start-the-agent.md
    - Lab 3 Semantic Search: lab-3-mcp-semantic-search.md
  - Observability Labs:
    - Observability Overview: observability-overview.md
    - Lab 4 Service Monitoring: lab-4-monitoring.md
    - Lab 5 Understand Tracing: lab-6-tracing.md
    # - Lab 6 Continuous Evaluation: lab-5-continuous-evaluation.md
  - Finishing Up: lab-7-finishing-up.md
  - Summary: summary.md
  - Resources: resources.md
  - Home Work:
    - Debugging with Dev Tunnel: hw-1-start-mcp-server.md
  - About: about.md


plugins:
  - search
  - glightbox
  - include-markdown
  - timetoread:
      wpm: 180
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
        - locale: es
          name: Español
          site_name: Desbloquea el Potencial de tu Agente con MCP
          admonition_translations:
            tip: Consejo
            warning: Advertencia
            info: Información
            note: Nota
            danger: Peligro
            success: Éxito
            question: Pregunta
          nav_translations:
            "Workshop Introduction": "Introducción al Taller"
            "Workshop Navigation": "Navegación del Taller"
            "Getting Started": "Comenzando"
            "Open the Workshop": "Abrir el Taller"
            "Star the GitHub Repo": "Marcar con Estrella el Repositorio GitHub"
            "Solution Architecture": "Arquitectura de la Solución"
            "What is an MCP Server": "Qué es un Servidor MCP"
            "Deploy Azure Resources": "Desplegar Recursos de Azure"
            "Open Workspace": "Abrir Espacio de Trabajo"
            "Agent Services Labs": "Laboratorios de Servicios de Agentes"
            "AI Foundry Agent Services": "Servicios de Agentes AI Foundry"
            "Lab 1 Agent Instructions": "Lab 1 Instrucciones del Agente"
            "Lab 2 Start your Agent": "Lab 2 Iniciar tu Agente"
            "Lab 3 Semantic Search MCP Tool": "Lab 3 Herramienta MCP de Búsqueda Semántica"
            "Observability Labs": "Laboratorios de Observabilidad"
            "Observability Overview": "Visión General de Observabilidad"
            "Lab 4 Service Monitoring": "Lab 4 Monitoreo de Servicios"
            "Lab 5 Continuous Evaluation": "Lab 5 Evaluación Continua"
            "Lab 6 Understand Tracing": "Lab 6 Entender el Trazado"
            "Security": "Seguridad"
            "Finishing Up": "Finalizando"
            "Home Work": "Tarea"
            "Debugging with Dev Tunnel": "Depuración con Dev Tunnel"
            "Summary": "Resumen"
            "Resources": "Recursos"
            "About": "Acerca de"
        - locale: hi
          name: हिंदी
          site_name: Model Context Protocol के साथ अपने Agent की क्षमता को अनलॉक करें
          admonition_translations:
            tip: टिप
            warning: चेतावनी
            info: जानकारी
            note: नोट
            danger: खतरा
            success: सफलता
            question: प्रश्न
          nav_translations:
            "Workshop Introduction": "वर्कशॉप परिचय"
            "Workshop Navigation": "वर्कशॉप नेविगेशन"
            "Getting Started": "शुरुआत करना"
            "Open the Workshop": "वर्कशॉप खोलना"
            "Star the GitHub Repo": "GitHub रिपो को स्टार करना"
            "Solution Architecture": "समाधान आर्किटेक्चर"
            "What is an MCP Server": "MCP सर्वर क्या है"
            "Deploy Azure Resources": "Azure संसाधन तैनात करना"
            "Open Workspace": "वर्कस्पेस खोलना"
            "Agent Services Labs": "एजेंट सेवाएं लैब्स"
            "AI Foundry Agent Services": "AI Foundry एजेंट सेवाएं"
            "Lab 1 Agent Instructions": "लैब 1 एजेंट निर्देश"
            "Lab 2 Start your Agent": "लैब 2 अपना एजेंट शुरू करना"
            "Lab 3 Semantic Search": "लैब 3 सिमेंटिक सर्च"
            "Observability Labs": "ऑब्जर्वेबिलिटी लैब्स"
            "Observability Overview": "ऑब्जर्वेबिलिटी ओवरव्यू"
            "Lab 4 Service Monitoring": "लैब 4 सेवा निगरानी"
            "Lab 5 Continuous Evaluation": "लैब 5 निरंतर मूल्यांकन"
            "Lab 6 Understand Tracing": "लैब 6 ट्रेसिंग को समझना"
            "Security": "सुरक्षा"
            "Finishing Up": "समाप्ति"
            "Home Work": "होम वर्क"
            "Debugging with Dev Tunnel": "Dev Tunnel के साथ डिबगिंग"
            "Summary": "सारांश"
            "Resources": "संसाधन"
            "About": "के बारे में"


theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky 
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - css/custom.css


