site_name: Unlock your Agents Potential with MCP
site_author: Dave Glover
site_description: >-
  Azure AI Foundry Agent Services with MCP Workshop.


# Repository ..................................................
repo_name: Unlock your Agents Potential with MCP
repo_url: https://github.com/microsoft/aitour26-WRK540-unlock-your-agents-potential-with-model-context-protocol

# Copyright ...................................................
copyright: >
  Copyright &copy; 2023 - present Microsoft


nav:
  - Workshop Introduction: index.md
  - Workshop Navigation: navigating-the-workshop.md
  - Getting Started: 
    - Open the Workshop: getting-started.md
    - Star the GitHub Repo: getting_started-star-workshop.md
    - Architecture Overview: architecture.md
    - Deploy Agent Resources: getting-started-azure.md
    - Open VS Code Workspace: getting-started-workspace.md
  - Agent Services Labs:
    - AI Foundry Agent Services: agent-service-overview.md
    - Lab 1 Agent Instructions: lab-1-agent-instructions.md
    - Lab 2 Start your Agent: lab-2-start-the-agent.md
    - Lab 3 Semantic Search: lab-3-mcp-semantic-search.md
  - Observability Labs:
    - Observability Overview: observability-overview.md
    - Lab 4 Service Monitoring: lab-4-monitoring.md
    - Lab 5 Understand Tracing: lab-6-tracing.md
    # - Lab 6 Continuous Evaluation: lab-5-continuous-evaluation.md
  - Finishing Up: lab-7-finishing-up.md
  - Summary: summary.md
  - Resources: resources.md
  - Home Work:
    - Debugging with Dev Tunnel: hw-1-start-mcp-server.md
  - About: about.md


plugins:
  - search
  - glightbox
  - include-markdown
  - timetoread:
      wpm: 180
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          site_name: Unlock your Agents Potential with MCP
          admonition_translations:
            tip: tip
            warning: Warning
            info: Information
            note: Note
            danger: Danger
            success: Success
            question: Question
          nav_translations:
            "Workshop Introduction": "Workshop Introduction"
            "Workshop Navigation": "Workshop Navigation"
            "Getting Started": "Getting Started"
            "Open the Workshop": "Open the Workshop"
            "Star the GitHub Repo": "Star the GitHub Repo"
            "Architecture Overview": "Architecture Overview"
            "Deploy Agent Resources": "Deploy Agent Resources"
            "Open VS Code Workspace": "Open VS Code Workspace"
            "Agent Services Labs": "Agent Services Labs"
            "AI Foundry Agent Services": "AI Foundry Agent Services"
            "Lab 1 Agent Instructions": "Lab 1 Agent Instructions"
            "Lab 2 Start your Agent": "Lab 2 Start your Agent"
            "Lab 3 Semantic Search": "Lab 3 Semantic Search"
            "Observability Labs": "Observability Labs"
            "Observability Overview": "Observability Overview"
            "Lab 4 Service Monitoring": "Lab 4 Service Monitoring"
            "Lab 5 Understand Tracing": "Lab 5 Understand Tracing"
            "Lab 6 Continuous Evaluation": "Lab 6 Continuous Evaluation"
            "Finishing Up": "Finishing Up"
            "Summary": "Summary"
            "Resources": "Resources"
            "Home Work": "Home Work"
            "Debugging with Dev Tunnel": "Debugging with Dev Tunnel"
            "About": "About"
        - locale: hi
          name: हिंदी
          site_name: MCP के साथ अपने एजेंट की क्षमता अनलॉक करें
          admonition_translations:
            tip: सुझाव
            warning: चेतावनी
            info: जानकारी
            note: नोट
            danger: खतरा
            success: सफल
            question: प्रश्न
          nav_translations:
            "Workshop Introduction": "वर्कशॉप परिचय"
            "Workshop Navigation": "वर्कशॉप नेविगेशन"
            "Getting Started": "शुरू करें"
            "Open the Workshop": "वर्कशॉप खोलें"
            "Star the GitHub Repo": "GitHub रेपो को स्टार करें"
            "Architecture Overview": "आर्किटेक्चर अवलोकन"
            "Deploy Agent Resources": "एजेंट संसाधन परिनियोजित करें"
            "Open VS Code Workspace": "VS Code वर्कस्पेस खोलें"
            "Agent Services Labs": "एजेंट सर्विस लैब्स"
            "AI Foundry Agent Services": "AI Foundry एजेंट सर्विस"
            "Lab 1 Agent Instructions": "लैब 1 एजेंट निर्देश"
            "Lab 2 Start your Agent": "लैब 2 एजेंट शुरू करें"
            "Lab 3 Semantic Search": "लैब 3 सेमान्टिक सर्च"
            "Observability Labs": "ऑब्ज़रवेबिलिटी लैब्स"
            "Observability Overview": "ऑब्ज़रवेबिलिटी अवलोकन"
            "Lab 4 Service Monitoring": "लैब 4 सेवा मॉनिटरिंग"
            "Lab 5 Understand Tracing": "लैब 5 ट्रेसिंग समझें"
            "Lab 6 Continuous Evaluation": "लैब 6 सतत मूल्यांकन"
            "Finishing Up": "समापन"
            "Summary": "सारांश"
            "Resources": "संसाधन"
            "Home Work": "होम वर्क"
            "Debugging with Dev Tunnel": "Dev Tunnel से डिबगिंग"
            "About": "परिचय"


theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky 
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - css/custom.css


