site_name: Unlock your Agents Potential with MCP
site_author: Dave Glover
site_description: >-
  Azure AI Foundry Agent Services with MCP Workshop.


# Repository ..................................................
repo_name: Unlock your Agents Potential with MCP
repo_url: https://github.com/microsoft/aitour26-WRK540-unlock-your-agents-potential-with-model-context-protocol

# Copyright ...................................................
copyright: >
  Copyright &copy; 2023 - present Microsoft


nav:
  - Workshop Introduction: index.md
  - Workshop Navigation: navigating-the-workshop.md
  - Getting Started: 
    - Open the Workshop: getting-started.md
    - Star the GitHub Repo: getting_started-star-workshop.md
    - Solution Architecture: architecture.md
    - What is an MCP Server: mcp-overview.md
    - Deploy Azure Resources: getting-started-azure.md
    - Open Workspace: getting-started-workspace.md
  - Agent Services Labs:
    - AI Foundry Agent Services: agent-service-overview.md
    - Lab 1 Agent Instructions: lab-1-agent-instructions.md
    - Lab 2 Start your Agent: lab-2-start-the-agent.md
    - Lab 3 Semantic Search MCP Tool: lab-3-mcp-semantic-search.md
  - Observability Labs:
    - Observability Overview: observability-overview.md
    - Lab 4 Service Monitoring: lab-4-monitoring.md
    - Lab 5 Continuous Evaluation: lab-5-continuous-evaluation.md
    - Lab 6 Understand Tracing: lab-6-tracing.md
  - Security: security.md
  - Finishing Up: lab-7-finishing-up.md
  - Home Work:
    - Debugging with Dev Tunnel: hw-1-start-mcp-server.md
  - Summary: summary.md
  - Resources: resources.md
  - About: about.md
  # - Deployment: deployment.md
  # - Troubleshooting: troubleshooting.md


plugins:
  - search
  - glightbox
  - include-markdown
  - timetoread:
      wpm: 180
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
        - locale: fr
          name: Français
          site_name: Atelier AI Tour 26
          admonition_translations:
            tip: Conseil
            warning: Avertissement
            info: Information
            note: Remarque
            danger: Danger
            success: Succès
            question: Question
          nav_translations:
            "Workshop Introduction": "Introduction à l'Atelier"
            "Workshop Navigation": "Navigation de l'Atelier"
            "Getting Started": "Pour Commencer"
            "Open the Workshop": "Ouvrir l'Atelier"
            "Star the GitHub Repo": "Marquer d'une Étoile le Dépôt GitHub"
            "Solution Architecture": "Architecture de la Solution"
            "What is an MCP Server": "Qu'est-ce qu'un Serveur MCP"
            "Deploy Azure Resources": "Déployer les Ressources Azure"
            "Open Workspace": "Ouvrir l'Espace de Travail"
            "Agent Services Labs": "Laboratoires de Services d'Agents"
            "AI Foundry Agent Services": "Services d'Agents AI Foundry"
            "Lab 1 Agent Instructions": "Lab 1 Instructions de l'Agent"
            "Lab 2 Start your Agent": "Lab 2 Démarrer votre Agent"
            "Lab 3 Semantic Search MCP Tool": "Lab 3 Outil de Recherche Sémantique MCP"
            "Observability Labs": "Laboratoires d'Observabilité"
            "Observability Overview": "Vue d'ensemble de l'Observabilité"
            "Lab 4 Service Monitoring": "Lab 4 Surveillance du Service"
            "Lab 5 Continuous Evaluation": "Lab 5 Évaluation Continue"
            "Lab 6 Understand Tracing": "Lab 6 Comprendre le Traçage"
            "Security": "Sécurité"
            "Finishing Up": "Finalisation"
            "Home Work": "Travaux à Domicile"
            "Debugging with Dev Tunnel": "Débogage avec Dev Tunnel"
            "Summary": "Résumé"
            "Resources": "Ressources"
            "About": "À propos"
        - locale: ja
          name: 日本語
          site_name: MCP でエージェントの可能性を解き放つ
          admonition_translations:
            tip: ヒント
            warning: 警告
            info: 情報
            note: 注意
            danger: 危険
            success: 成功
            question: 質問
          nav_translations:
            "Workshop Introduction": "ワークショップ紹介"
            "Workshop Navigation": "ワークショップナビゲーション"
            "Getting Started": "はじめに"
            "Open the Workshop": "ワークショップを開く"
            "Star the GitHub Repo": "GitHub リポジトリにスターを付ける"
            "Solution Architecture": "ソリューションアーキテクチャ"
            "What is an MCP Server": "MCP サーバーとは"
            "Deploy Azure Resources": "Azure リソースをデプロイする"
            "Open Workspace": "ワークスペースを開く"
            "Agent Services Labs": "エージェントサービスラボ"
            "AI Foundry Agent Services": "AI Foundry エージェントサービス"
            "Lab 1 Agent Instructions": "ラボ1 エージェント指示"
            "Lab 2 Start your Agent": "ラボ2 エージェントを開始する"
            "Lab 3 Semantic Search MCP Tool": "ラボ3 セマンティック検索 MCP ツール"
            "Observability Labs": "可観測性ラボ"
            "Observability Overview": "可観測性概要"
            "Lab 4 Service Monitoring": "ラボ4 サービス監視"
            "Lab 5 Continuous Evaluation": "ラボ5 継続的評価"
            "Lab 6 Understand Tracing": "ラボ6 トレーシングの理解"
            "Security": "セキュリティ"
            "Finishing Up": "仕上げ"
            "Home Work": "ホームワーク"
            "Debugging with Dev Tunnel": "Dev Tunnel でのデバッグ"
            "Summary": "まとめ"
            "Resources": "リソース"
            "About": "概要"
        - locale: es
          name: Español
          site_name: Desbloquea el Potencial de tu Agente con MCP
          admonition_translations:
            tip: Consejo
            warning: Advertencia
            info: Información
            note: Nota
            danger: Peligro
            success: Éxito
            question: Pregunta
          nav_translations:
            "Workshop Introduction": "Introducción al Taller"
            "Workshop Navigation": "Navegación del Taller"
            "Getting Started": "Comenzando"
            "Open the Workshop": "Abrir el Taller"
            "Star the GitHub Repo": "Marcar con Estrella el Repositorio GitHub"
            "Solution Architecture": "Arquitectura de la Solución"
            "What is an MCP Server": "Qué es un Servidor MCP"
            "Deploy Azure Resources": "Desplegar Recursos de Azure"
            "Open Workspace": "Abrir Espacio de Trabajo"
            "Agent Services Labs": "Laboratorios de Servicios de Agentes"
            "AI Foundry Agent Services": "Servicios de Agentes AI Foundry"
            "Lab 1 Agent Instructions": "Lab 1 Instrucciones del Agente"
            "Lab 2 Start your Agent": "Lab 2 Iniciar tu Agente"
            "Lab 3 Semantic Search MCP Tool": "Lab 3 Herramienta MCP de Búsqueda Semántica"
            "Observability Labs": "Laboratorios de Observabilidad"
            "Observability Overview": "Visión General de Observabilidad"
            "Lab 4 Service Monitoring": "Lab 4 Monitoreo de Servicios"
            "Lab 5 Continuous Evaluation": "Lab 5 Evaluación Continua"
            "Lab 6 Understand Tracing": "Lab 6 Entender el Trazado"
            "Security": "Seguridad"
            "Finishing Up": "Finalizando"
            "Home Work": "Tarea"
            "Debugging with Dev Tunnel": "Depuración con Dev Tunnel"
            "Summary": "Resumen"
            "Resources": "Recursos"
            "About": "Acerca de"
        - locale: it
          name: Italiano
          site_name: Sblocca il Potenziale del Tuo Agente con MCP
          admonition_translations:
            tip: Suggerimento
            warning: Avvertimento
            info: Informazione
            note: Nota
            danger: Pericolo
            success: Successo
            question: Domanda
          nav_translations:
            "Workshop Introduction": "Introduzione al Workshop"
            "Workshop Navigation": "Navigazione del Workshop"
            "Getting Started": "Iniziare"
            "Open the Workshop": "Aprire il Workshop"
            "Star the GitHub Repo": "Mettere una Stella al Repository GitHub"
            "Solution Architecture": "Architettura della Soluzione"
            "What is an MCP Server": "Cos'è un Server MCP"
            "Deploy Azure Resources": "Distribuire Risorse Azure"
            "Open Workspace": "Aprire il Workspace"
            "Agent Services Labs": "Laboratori Servizi Agente"
            "AI Foundry Agent Services": "Servizi Agente AI Foundry"
            "Lab 1 Agent Instructions": "Lab 1 Istruzioni Agente"
            "Lab 2 Start your Agent": "Lab 2 Avviare il tuo Agente"
            "Lab 3 Semantic Search MCP Tool": "Lab 3 Strumento MCP Ricerca Semantica"
            "Observability Labs": "Laboratori Osservabilità"
            "Observability Overview": "Panoramica Osservabilità"
            "Lab 4 Service Monitoring": "Lab 4 Monitoraggio Servizi"
            "Lab 5 Continuous Evaluation": "Lab 5 Valutazione Continua"
            "Lab 6 Understand Tracing": "Lab 6 Comprendere il Tracing"
            "Security": "Sicurezza"
            "Finishing Up": "Completamento"
            "Home Work": "Compiti a Casa"
            "Debugging with Dev Tunnel": "Debug con Dev Tunnel"
            "Summary": "Riassunto"
            "Resources": "Risorse"
            "About": "Informazioni"
        - locale: ar
          name: العربية
          site_name: اطلق إمكانات وكيلك مع بروتوكول سياق النموذج
          admonition_translations:
            tip: نصيحة
            warning: تحذير
            info: معلومات
            note: ملاحظة
            danger: خطر
            success: نجاح
            question: سؤال
          nav_translations:
            "Workshop Introduction": "مقدمة الورشة"
            "Workshop Navigation": "التنقل في الورشة"
            "Getting Started": "البدء"
            "Open the Workshop": "فتح الورشة"
            "Star the GitHub Repo": "وضع نجمة على مستودع GitHub"
            "Solution Architecture": "بنية الحل"
            "What is an MCP Server": "ما هو خادم MCP"
            "Deploy Azure Resources": "نشر موارد Azure"
            "Open Workspace": "فتح مساحة العمل"
            "Agent Services Labs": "مختبرات خدمات الوكلاء"
            "AI Foundry Agent Services": "خدمات وكلاء AI Foundry"
            "Lab 1 Agent Instructions": "المختبر 1 تعليمات الوكيل"
            "Lab 2 Start your Agent": "المختبر 2 ابدأ وكيلك"
            "Lab 3 Semantic Search MCP Tool": "المختبر 3 أداة البحث الدلالي MCP"
            "Observability Labs": "مختبرات قابلية المراقبة"
            "Observability Overview": "نظرة عامة على قابلية المراقبة"
            "Lab 4 Service Monitoring": "المختبر 4 مراقبة الخدمة"
            "Lab 5 Continuous Evaluation": "المختبر 5 التقييم المستمر"
            "Lab 6 Understand Tracing": "المختبر 6 فهم التتبع"
            "Security": "الأمان"
            "Finishing Up": "الانتهاء"
            "Home Work": "الواجب المنزلي"
            "Debugging with Dev Tunnel": "التصحيح مع Dev Tunnel"
            "Summary": "الملخص"
            "Resources": "الموارد"
            "About": "حول"
        - locale: hi
          name: हिन्दी
          site_name: Model Context Protocol के साथ अपने Agent की क्षमता को अनलॉक करें
          admonition_translations:
            tip: सुझाव
            warning: चेतावनी
            info: जानकारी
            note: नोट
            danger: खतरा
            success: सफलता
            question: प्रश्न
          nav_translations:
            "Workshop Introduction": "कार्यशाला परिचय"
            "Workshop Navigation": "कार्यशाला नेविगेशन"
            "Getting Started": "प्रारंभ करना"
            "Open the Workshop": "कार्यशाला खोलें"
            "Star the GitHub Repo": "GitHub रिपो को Star करें"
            "Solution Architecture": "समाधान आर्किटेक्चर"
            "What is an MCP Server": "MCP सर्वर क्या है"
            "Deploy Azure Resources": "Azure संसाधन तैनात करें"
            "Open Workspace": "कार्यक्षेत्र खोलें"
            "Agent Services Labs": "एजेंट सेवा लैब्स"
            "AI Foundry Agent Services": "AI Foundry एजेंट सेवाएं"
            "Lab 1 Agent Instructions": "लैब 1 एजेंट निर्देश"
            "Lab 2 Start your Agent": "लैब 2 अपना एजेंट शुरू करें"
            "Lab 3 Semantic Search MCP Tool": "लैब 3 सिमेंटिक सर्च MCP टूल"
            "Observability Labs": "अवलोकनीयता लैब्स"
            "Observability Overview": "अवलोकनीयता अवलोकन"
            "Lab 4 Service Monitoring": "लैब 4 सेवा निगरानी"
            "Lab 5 Continuous Evaluation": "लैब 5 निरंतर मूल्यांकन"
            "Lab 6 Understand Tracing": "लैब 6 ट्रेसिंग समझें"
            "Security": "सुरक्षा"
            "Finishing Up": "समाप्ति"
            "Home Work": "गृह कार्य"
            "Debugging with Dev Tunnel": "Dev Tunnel के साथ डिबगिंग"
            "Summary": "सारांश"
            "Resources": "संसाधन"
            "About": "के बारे में"
        - locale: ko
          name: 한국어
          site_name: MCP로 에이전트의 잠재력 발휘하기
          admonition_translations:
            tip: 팁
            warning: 경고
            info: 정보
            note: 참고
            danger: 위험
            success: 성공
            question: 질문
          nav_translations:
            "Workshop Introduction": "워크샵 소개"
            "Workshop Navigation": "워크샵 내비게이션"
            "Getting Started": "시작하기"
            "Open the Workshop": "워크샵 열기"
            "Star the GitHub Repo": "GitHub 리포지토리 별표 표시"
            "Solution Architecture": "솔루션 아키텍처"
            "What is an MCP Server": "MCP 서버란"
            "Deploy Azure Resources": "Azure 리소스 배포"
            "Open Workspace": "워크스페이스 열기"
            "Agent Services Labs": "에이전트 서비스 랩"
            "AI Foundry Agent Services": "AI Foundry 에이전트 서비스"
            "Lab 1 Agent Instructions": "랩 1 에이전트 지침"
            "Lab 2 Start your Agent": "랩 2 에이전트 시작"
            "Lab 3 Semantic Search MCP Tool": "랩 3 시맨틱 검색 MCP 도구"
            "Observability Labs": "관찰 가능성 랩"
            "Observability Overview": "관찰 가능성 개요"
            "Lab 4 Service Monitoring": "랩 4 서비스 모니터링"
            "Lab 5 Continuous Evaluation": "랩 5 지속적 평가"
            "Lab 6 Understand Tracing": "랩 6 추적 이해"
            "Security": "보안"
            "Finishing Up": "마무리"
            "Home Work": "과제"
            "Debugging with Dev Tunnel": "Dev Tunnel로 디버깅"
            "Summary": "요약"
            "Resources": "리소스"
            "About": "소개"
        - locale: nl
          name: Nederlands
          site_name: Ontgrendel het Potentieel van je Agent met MCP
          admonition_translations:
            tip: Tip
            warning: Waarschuwing
            info: Informatie
            note: Opmerking
            danger: Gevaar
            success: Succes
            question: Vraag
          nav_translations:
            "Workshop Introduction": "Workshop Introductie"
            "Workshop Navigation": "Workshop Navigatie"
            "Getting Started": "Aan de Slag"
            "Open the Workshop": "Workshop Openen"
            "Star the GitHub Repo": "GitHub Repo Sterren"
            "Solution Architecture": "Oplossingsarchitectuur"
            "What is an MCP Server": "Wat is een MCP Server"
            "Deploy Azure Resources": "Azure Resources Implementeren"
            "Open Workspace": "Workspace Openen"
            "Agent Services Labs": "Agent Services Labs"
            "AI Foundry Agent Services": "AI Foundry Agent Services"
            "Lab 1 Agent Instructions": "Lab 1 Agent Instructies"
            "Lab 2 Start your Agent": "Lab 2 Start je Agent"
            "Lab 3 Semantic Search MCP Tool": "Lab 3 Semantische Zoek MCP Tool"
            "Observability Labs": "Observeerbaarheid Labs"
            "Observability Overview": "Observeerbaarheid Overzicht"
            "Lab 4 Service Monitoring": "Lab 4 Service Monitoring"
            "Lab 5 Continuous Evaluation": "Lab 5 Continue Evaluatie"
            "Lab 6 Understand Tracing": "Lab 6 Tracing Begrijpen"
            "Security": "Beveiliging"
            "Finishing Up": "Afronden"
            "Home Work": "Huiswerk"
            "Debugging with Dev Tunnel": "Debuggen met Dev Tunnel"
            "Summary": "Samenvatting"
            "Resources": "Resources"
            "About": "Over"

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky 
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular
  # logo: docs/media/azure-ai-studio.svg
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - css/custom.css


